### ISSUE TITLE
Please let me know if this is an issue?

### ISSUE THREAD

**Issue by mebalzer** [OSVR/OSVR-Android-Build#19]
This error was caused with the latest Clone with recursion, CrystaxNDK 10.1 as suggested with the latest CMake and Boost (1.60) libraries.

FAILED: cmd.exe /C "cd . && E:\crystax-ndk\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-g++.exe  -fPIC -fexceptions -frtti -Wno-psabi --sysroot=E:/crystax-ndk/platforms/android-16/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fdata-sections -ffunction-sections -Wa,--noexecstack  -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,muldefs -shared -Wl,-soname, -o lib\osvr-plugins-0\org_osvr_filter_videoimufusion.so plugins/videoimufusion/CMakeFiles/org_osvr_filter_videoimufusion.dir/RunningData.cpp.o plugins/videoimufusion/CMakeFiles/org_osvr_filter_videoimufusion.dir/RunningDataPredictCorrect.cpp.o plugins/videoimufusion/CMakeFiles/org_osvr_filter_videoimufusion.dir/VideoIMUFusion.cpp.o plugins/videoimufusion/CMakeFiles/org_osvr_filter_videoimufusion.dir/org_osvr_filter_videoimufusion.cpp.o plugins/videoimufusion/CMakeFiles/org_osvr_filter_videoimufusion.dir/VideoIMUFusionDevice.cpp.o -LE:/crystax-ndk/sources/crystax/empty  -LE:/OSVR-Android-Build/build/install/libs/armeabi-v7a lib/libosvrAnalysisPluginKit.so lib/libosvrPluginKit.so lib/libosvrClientKit.so lib/libosvrUtil.so E:/OSVR-Android-Build/build/install/lib/libjsoncpp.so -Wl,-rpath-link,E:/OSVR-Android-Build/build/src/OSVR-Core-prefix/src/OSVR-Core-build/lib:E:/OSVR-Android-Build/build/install/lib "E:/crystax-ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_shared.so" "E:/crystax-ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a"  E:/crystax-ndk/sources/crystax/libs/armeabi-v7a/libcrystax.so -lc && cd ."
plugins/videoimufusion/CMakeFiles/org_osvr_filter_videoimufusion.dir/VideoIMUFusion.cpp.o:VideoIMUFusion.cpp:function VideoIMUFusion::enterRunningState(Eigen::Transform<double, 3, 1, 0> const&, OSVR_TimeValue const&, OSVR_PoseReport const&, OSVR_Quaternion const&): error: undefined reference to 'VideoIMUFusion::RunningData::RunningData(VideoIMUFusionParams const&, Eigen::Transform<double, 3, 1, 0> const&, OSVR_Quaternion const&, OSVR_Pose3 const&, OSVR_TimeValue const&)'
collect2.exe: error: ld returned 1 exit status

**Comment by JeroMiya** [comment]
Looks like we need to exclude the videoimufusion plugin from the Android build. Thanks for the report!

**Comment by mebalzer** [comment]
Do you have time-frame when this will be done or is it something I can do. Sadly I am on a tight-schedule to get a build done to test the OSVR for own hardware inclusion.  Thanks!

**Comment by rpavlik** [comment]
It's been merged now.
