### ISSUE TITLE
OSVR-RenderManager Refuses To Clone Recursively

### ISSUE THREAD

**Issue by Balderick** [OSVR/OSVR-Android-Build#30]
Using `git clone --recursive https://github.com/OSVR/OSVR-Android-Build.git` clones all the osvr-core submodules as expected until

````
Cloning into 'D:/OSVR-Android-Build/src/OSVR-RenderManager/osvr/RenderKit/NDA/OSVR-RenderManager-AMD'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:sensics/OSVR-RenderManager-AMD.git' into submodule path 'D:/OSVR-Android-Build/src/OSVR-RenderManager/osvr/RenderKit/NDA/OSVR-RenderManager-AMD' failed
Failed to clone 'osvr/RenderKit/NDA/OSVR-RenderManager-AMD'. Retry scheduled
Cloning into 'D:/OSVR-Android-Build/src/OSVR-RenderManager/osvr/RenderKit/NDA/OSVR-RenderManager-Intel'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:sensics/OSVR-RenderManager-Intel.git' into submodule path 'D:/OSVR-Android-Build/src/OSVR-RenderManager/osvr/RenderKit/NDA/OSVR-RenderManager-Intel' failed
Failed to clone 'osvr/RenderKit/NDA/OSVR-RenderManager-Intel'. Retry scheduled
Cloning into 'D:/OSVR-Android-Build/src/OSVR-RenderManager/osvr/RenderKit/NDA/OSVR-RenderManager-NVIDIA'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:sensics/OSVR-RenderManager-NVIDIA.git' into submodule path 'D:/OSVR-Android-Build/src/OSVR-RenderManager/osvr/RenderKit/NDA/OSVR-RenderManager-NVIDIA' failed
Failed to clone 'osvr/RenderKit/NDA/OSVR-RenderManager-NVIDIA'. Retry scheduled
Cloning into 'D:/OSVR-Android-Build/src/OSVR-RenderManager/osvr/RenderKit/NDA/OSVR-RenderManager-Sensics'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:sensics/OSVR-RenderManager-Sensics.git' into submodule path 'D:/OSVR-Android-Build/src/OSVR-RenderManager/osvr/RenderKit/NDA/OSVR-RenderManager-Sensics' failed
Failed to clone 'osvr/RenderKit/NDA/OSVR-RenderManager-Sensics'. Retry scheduled
Cloning into 'D:/OSVR-Android-Build/src/OSVR-RenderManager/vendor/vrpn'...
Cloning into 'D:/OSVR-Android-Build/src/OSVR-RenderManager/osvr/RenderKit/NDA/OSVR-RenderManager-AMD'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:sensics/OSVR-RenderManager-AMD.git' into submodule path 'D:/OSVR-Android-Build/src/OSVR-RenderManager/osvr/RenderKit/NDA/OSVR-RenderManager-AMD' failed
Failed to clone 'osvr/RenderKit/NDA/OSVR-RenderManager-AMD' a second time, aborting
Submodule path 'src/android_sensor_tracker': checked out '9f315ec7b0c4dc8d880d23210dfecbb82be954be'
Submodule path 'src/boost': checked out '5f734dab307c550b93731606d55f776833270e7c'
Submodule path 'src/hidapi': checked out 'a6a622ffb680c55da0de787ff93b80280498330f'
Submodule path 'src/jsoncpp': checked out '0f6884f771eae221873b345af2c6369ccf7dcb5b'
Submodule path 'src/libfunctionality': checked out '3c8b1e4d21283eed346ee17d95d270c9a1d97db9'
Submodule path 'src/libusb': checked out 'b06b4d101b5ddd95e86a6ba34b526eda6fc839ba'
Failed to recurse into submodule path 'src/OSVR-RenderManager'

C:\Program Files (x86)\Microsoft Visual Studio 14.0>
````

We need all sub modules to clone recursively.

**Comment by godbyk** [comment]
You can't clone all the RM submodules because they include the NDA submodules that aren't publicly accessible.  You'll need to manually initialize the `vendor/vrpn` submodule as per the instructions in the [README](https://github.com/sensics/OSVR-RenderManager#readme).

**Comment by Balderick** [comment]
The whole point of using the --recursive option is so that the init call and update call are not needed that is according to the "Cloning A Project With Submodules" section of  https://git-scm.com/book/en/v2/Git-Tools-Submodules and is why using --recursive is advised as the first step of this [readme](https://github.com/OSVR/OSVR-Android-Build/blob/master/README.md)

**Comment by godbyk** [comment]
I'm aware of the usefulness of the `--recursive` option. I'm just explaining why it's not working for you in this instance.

**Comment by Balderick** [comment]
Let me try to expand on why this is an issue.   Basically not one of the osvr android projects are either compiling as expected nor are the pre compiled binaries or apks working as expected and all because of the issue described here.

When I try to compile or run  osvr-unity-palace demo from  https://github.com/OSVR/OSVR-Unity-Palace-Demo/tree/androidPalace all I get is a full screen demo with no head tracking or SBS.   No osvr server notifications and no access to any osvr components to configure osvr server etc
This is because the SRC dependencies for osvr render manager which provide all the distortion, trackers etc have never been created for that package.

Osvr androidserver launcher does not work because of this issue of render manager not compiling from source.

Osvr android samples do not work because of this issue of render manager not compiling from source.

None of the readmess for these projects provide information on how to actually get a working project.

Reminding me of how I can manually get the source for render manager does not help me in getting any of these projects to work as  I have not worked out how to merge that source into any of the other projects which depend on it  yet

**Comment by JeroMiya** [comment]
OSVR on Android is going through an overhaul at the moment, to get everything working with the latest SDK and build tools. Builds that used to work may be broken with more recent SDKs.

For android, the only submodule of RenderManager that you need is the vrpn one. None of the NDA modules are used for the Android build, so you'll be good there. The bigger problem is updating OSVR to work on the latest SDK. For instance, plugin loading doesn't currently work when you set your target SDK to anything greater than 21 (working on a fix).

As soon as I get a working build onto master again, I'll see about updating the documentation for both the OSVR-Android-Build project and the OSVR-Android-Samples project.

**Comment by Balderick** [comment]
Thanks for the feedback.  I was looking at getting osvr software running on nvidia shield devices and was trying to compile for arm abi 24 as well as armv8a 64 bit for shield tv.  

It is great to see android support being worked on and look forward to seeing osvr being supported on android.
