### ISSUE TITLE
Building and testing README

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Android-Build#4]
The remaining piece of David's first Android port that hasn't been integrated is his documentation.  Some of it is irrelevant now (since we build jsoncpp, libfunctionality, libusb, hidapi, etc. in this build, and have android-cmake as a submodule), while some is still relevant.

So I can close the other branch, I've put the content (just slightly formatted) up here in a gist: https://gist.github.com/rpavlik/b6024cba0d11c2b68bad

**Comment by rpavlik** [comment]
cc @davtbaum

**Comment by rpavlik** [comment]
So I think I have this solved, with the latest readme - @DuFF14 if you agree please close this issue.

**Comment by DuFF14** [comment]
looks good to me.
