### ISSUE TITLE
Decide on ANDROID_NATIVE_API_LEVEL

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Android-Build#6]
We need to decide what we'll require for `ANDROID_NATIVE_API_LEVEL` - I'm not sure what goes into that decision. I know CrystaX improves compatibility for older API levels, so if we stick with that NDK we probably can get away with a lower value. David had chosen 19 - not sure what the reasoning was, maybe he can chime in (@davtbaum?)

**Comment by DuFF14** [comment]
Google Cardboard requires a physical Android device running Android 16 (Jelly Bean) or higher. This might be a good place to start. 
https://developers.google.com/cardboard/android/get-started

**Comment by rpavlik** [comment]
I didn't see any relevant differences between 15 and 16 in the headers I expect that we use (did a comparison in the official NDK). Not sure which one is ICS, but ICS support would be handy if possible since I've got a cheapo tablet here that is easily (and already) rooted and running some old Android that I can't recall if it's ICS or JB.  FWIW, OpenCV only needs 8, though there have been barcode scanners and such for a long time...

**Comment by rpavlik** [comment]
Locally I've been trying 14, seems fine to me

**Comment by rpavlik** [comment]
This was resolved in order to handle PIE/PIC issues in Lollipop.
